/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guessing_game;

import java.util.Scanner;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.println("Let's play a guessing game! Please enter a number between 1 and 10:");
        int userInt = input.nextInt();
        int numberOfGuesses = 1;
        int maxNumberOfGuesses = 3;
        Random number = new Random();
        int min = 1;
        int max = 10;
        for (numberOfGuesses = 1; numberOfGuesses <= maxNumberOfGuesses; numberOfGuesses++) {
            int randomlyGeneratedNumber = number.nextInt(max) + min;
            if (userInt == randomlyGeneratedNumber) {
                System.out.println("Nice guess. You win!");
                break;
            } else if (userInt == 0) {
                System.out.println("Instructions: Please choose a number between 1 and 10.");
                numberOfGuesses = numberOfGuesses-1;
                userInt = input.nextInt();
            } else if (userInt == -1){
                System.out.println("You have chosen to exit the game.");
                break;
            } else {
                if (numberOfGuesses < maxNumberOfGuesses) {
                    System.out.println("Sorry, that's not the magic number. Please try again. That was guess # " + numberOfGuesses + " of 3.");
                    if(userInt > randomlyGeneratedNumber){
                        System.out.println("Hint. Hint. The number you guessed is too high.");
                    }else {
                        System.out.println("Hint. Hint. The number you guessed is too low.");
                    }
                    userInt = input.nextInt();
                } else {
                    System.out.println("Uh oh, " + numberOfGuesses + " strikes and you're out. You lost the guessing game!");
                }
            }
        }
        input.close();
    }
}