/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guessing_game;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.println("Please enter a number between 1 and 10:");
        int userInt = input.nextInt();
        if (userInt == 7){
            System.out.println("You win!");
        }
        else if (userInt == 0){
            System.out.println("You must have misunderstood the rules. Please enter a number from between 1 and 10.");
        }

        input.close();
    }
}
